serial:
  baud_rate: 1000000
  serial_port: /dev/tty.usbserial-A1MFJ76
  # parity could be even/odd/none/mark/space
  parity: none 
  # stop_bits could be 1/1.5/2
  stop_bits: 1
  # byte_size could be 5/6/7/8
  byte_size: 8  
  # flow_control could be true/false
  flow_control: True
  timeout: 1  


lights: [
  light1: {address: 0x4b9f, endpoint: 0x40}, 
  light2: {address: 0x27f4, endpoint: 0x40}
]

groups: [
  group1: {address: 0xaaab, endpoint: 0x40}
]